export default {
  a: (props = {}, ...children) => ({
    props,
    element: 'a',
    children,
    selfClosing: false,
  }),
  abbr: (props = {}, ...children) => ({
    props,
    element: 'abbr',
    children,
    selfClosing: false,
  }),
  address: (props = {}, ...children) => ({
    props,
    element: 'address',
    children,
    selfClosing: false,
  }),
  area: (props = {}, ...children) => ({
    props,
    element: 'area',
    children,
    selfClosing: true,
  }),
  article: (props = {}, ...children) => ({
    props,
    element: 'article',
    children,
    selfClosing: false,
  }),
  aside: (props = {}, ...children) => ({
    props,
    element: 'aside',
    children,
    selfClosing: false,
  }),
  audio: (props = {}, ...children) => ({
    props,
    element: 'audio',
    children,
    selfClosing: false,
  }),
  b: (props = {}, ...children) => ({
    props,
    element: 'b',
    children,
    selfClosing: false,
  }),
  base: (props = {}, ...children) => ({
    props,
    element: 'base',
    children,
    selfClosing: true,
  }),
  bdi: (props = {}, ...children) => ({
    props,
    element: 'bdi',
    children,
    selfClosing: false,
  }),
  bdo: (props = {}, ...children) => ({
    props,
    element: 'bdo',
    children,
    selfClosing: false,
  }),
  blockquote: (props = {}, ...children) => ({
    props,
    element: 'blockquote',
    children,
    selfClosing: false,
  }),
  body: (props = {}, ...children) => ({
    props,
    element: 'body',
    children,
    selfClosing: false,
  }),
  br: (props = {}, ...children) => ({
    props,
    element: 'br',
    children,
    selfClosing: true,
  }),
  button: (props = {}, ...children) => ({
    props,
    element: 'button',
    children,
    selfClosing: false,
  }),
  canvas: (props = {}, ...children) => ({
    props,
    element: 'canvas',
    children,
    selfClosing: false,
  }),
  caption: (props = {}, ...children) => ({
    props,
    element: 'caption',
    children,
    selfClosing: false,
  }),
  cite: (props = {}, ...children) => ({
    props,
    element: 'cite',
    children,
    selfClosing: false,
  }),
  code: (props = {}, ...children) => ({
    props,
    element: 'code',
    children,
    selfClosing: false,
  }),
  col: (props = {}, ...children) => ({
    props,
    element: 'col',
    children,
    selfClosing: true,
  }),
  colgroup: (props = {}, ...children) => ({
    props,
    element: 'colgroup',
    children,
    selfClosing: false,
  }),
  data: (props = {}, ...children) => ({
    props,
    element: 'data',
    children,
    selfClosing: false,
  }),
  datalist: (props = {}, ...children) => ({
    props,
    element: 'datalist',
    children,
    selfClosing: false,
  }),
  dd: (props = {}, ...children) => ({
    props,
    element: 'dd',
    children,
    selfClosing: false,
  }),
  del: (props = {}, ...children) => ({
    props,
    element: 'del',
    children,
    selfClosing: false,
  }),
  details: (props = {}, ...children) => ({
    props,
    element: 'details',
    children,
    selfClosing: false,
  }),
  dfn: (props = {}, ...children) => ({
    props,
    element: 'dfn',
    children,
    selfClosing: false,
  }),
  dialog: (props = {}, ...children) => ({
    props,
    element: 'dialog',
    children,
    selfClosing: false,
  }),
  div: (props = {}, ...children) => ({
    props,
    element: 'div',
    children,
    selfClosing: false,
  }),
  dl: (props = {}, ...children) => ({
    props,
    element: 'dl',
    children,
    selfClosing: false,
  }),
  dt: (props = {}, ...children) => ({
    props,
    element: 'dt',
    children,
    selfClosing: false,
  }),
  em: (props = {}, ...children) => ({
    props,
    element: 'em',
    children,
    selfClosing: false,
  }),
  embed: (props = {}, ...children) => ({
    props,
    element: 'embed',
    children,
    selfClosing: true,
  }),
  fieldset: (props = {}, ...children) => ({
    props,
    element: 'fieldset',
    children,
    selfClosing: false,
  }),
  figcaption: (props = {}, ...children) => ({
    props,
    element: 'figcaption',
    children,
    selfClosing: false,
  }),
  figure: (props = {}, ...children) => ({
    props,
    element: 'figure',
    children,
    selfClosing: false,
  }),
  footer: (props = {}, ...children) => ({
    props,
    element: 'footer',
    children,
    selfClosing: false,
  }),
  form: (props = {}, ...children) => ({
    props,
    element: 'form',
    children,
    selfClosing: false,
  }),
  h1: (props = {}, ...children) => ({
    props,
    element: 'h1',
    children,
    selfClosing: false,
  }),
  h2: (props = {}, ...children) => ({
    props,
    element: 'h2',
    children,
    selfClosing: false,
  }),
  h3: (props = {}, ...children) => ({
    props,
    element: 'h3',
    children,
    selfClosing: false,
  }),
  h4: (props = {}, ...children) => ({
    props,
    element: 'h4',
    children,
    selfClosing: false,
  }),
  h5: (props = {}, ...children) => ({
    props,
    element: 'h5',
    children,
    selfClosing: false,
  }),
  h6: (props = {}, ...children) => ({
    props,
    element: 'h6',
    children,
    selfClosing: false,
  }),
  head: (props = {}, ...children) => ({
    props,
    element: 'head',
    children,
    selfClosing: false,
  }),
  header: (props = {}, ...children) => ({
    props,
    element: 'header',
    children,
    selfClosing: false,
  }),
  hgroup: (props = {}, ...children) => ({
    props,
    element: 'hgroup',
    children,
    selfClosing: false,
  }),
  hr: (props = {}, ...children) => ({
    props,
    element: 'hr',
    children,
    selfClosing: true,
  }),
  html: (props = {}, ...children) => ({
    props,
    element: 'html',
    children,
    selfClosing: false,
  }),
  i: (props = {}, ...children) => ({
    props,
    element: 'i',
    children,
    selfClosing: false,
  }),
  iframe: (props = {}, ...children) => ({
    props,
    element: 'iframe',
    children,
    selfClosing: false,
  }),
  img: (props = {}, ...children) => ({
    props,
    element: 'img',
    children,
    selfClosing: true,
  }),
  input: (props = {}, ...children) => ({
    props,
    element: 'input',
    children,
    selfClosing: true,
  }),
  ins: (props = {}, ...children) => ({
    props,
    element: 'ins',
    children,
    selfClosing: false,
  }),
  kbd: (props = {}, ...children) => ({
    props,
    element: 'kbd',
    children,
    selfClosing: false,
  }),
  label: (props = {}, ...children) => ({
    props,
    element: 'label',
    children,
    selfClosing: false,
  }),
  legend: (props = {}, ...children) => ({
    props,
    element: 'legend',
    children,
    selfClosing: false,
  }),
  li: (props = {}, ...children) => ({
    props,
    element: 'li',
    children,
    selfClosing: false,
  }),
  link: (props = {}, ...children) => ({
    props,
    element: 'link',
    children,
    selfClosing: true,
  }),
  main: (props = {}, ...children) => ({
    props,
    element: 'main',
    children,
    selfClosing: false,
  }),
  map: (props = {}, ...children) => ({
    props,
    element: 'map',
    children,
    selfClosing: false,
  }),
  mark: (props = {}, ...children) => ({
    props,
    element: 'mark',
    children,
    selfClosing: false,
  }),
  meta: (props = {}, ...children) => ({
    props,
    element: 'meta',
    children,
    selfClosing: true,
  }),
  meter: (props = {}, ...children) => ({
    props,
    element: 'meter',
    children,
    selfClosing: false,
  }),
  nav: (props = {}, ...children) => ({
    props,
    element: 'nav',
    children,
    selfClosing: false,
  }),
  noscript: (props = {}, ...children) => ({
    props,
    element: 'noscript',
    children,
    selfClosing: false,
  }),
  object: (props = {}, ...children) => ({
    props,
    element: 'object',
    children,
    selfClosing: false,
  }),
  ol: (props = {}, ...children) => ({
    props,
    element: 'ol',
    children,
    selfClosing: false,
  }),
  optgroup: (props = {}, ...children) => ({
    props,
    element: 'optgroup',
    children,
    selfClosing: false,
  }),
  option: (props = {}, ...children) => ({
    props,
    element: 'option',
    children,
    selfClosing: false,
  }),
  output: (props = {}, ...children) => ({
    props,
    element: 'output',
    children,
    selfClosing: false,
  }),
  p: (props = {}, ...children) => ({
    props,
    element: 'p',
    children,
    selfClosing: false,
  }),
  param: (props = {}, ...children) => ({
    props,
    element: 'param',
    children,
    selfClosing: true,
  }),
  picture: (props = {}, ...children) => ({
    props,
    element: 'picture',
    children,
    selfClosing: false,
  }),
  pre: (props = {}, ...children) => ({
    props,
    element: 'pre',
    children,
    selfClosing: false,
  }),
  progress: (props = {}, ...children) => ({
    props,
    element: 'progress',
    children,
    selfClosing: false,
  }),
  q: (props = {}, ...children) => ({
    props,
    element: 'q',
    children,
    selfClosing: false,
  }),
  rp: (props = {}, ...children) => ({
    props,
    element: 'rp',
    children,
    selfClosing: false,
  }),
  rt: (props = {}, ...children) => ({
    props,
    element: 'rt',
    children,
    selfClosing: false,
  }),
  ruby: (props = {}, ...children) => ({
    props,
    element: 'ruby',
    children,
    selfClosing: false,
  }),
  s: (props = {}, ...children) => ({
    props,
    element: 's',
    children,
    selfClosing: false,
  }),
  samp: (props = {}, ...children) => ({
    props,
    element: 'samp',
    children,
    selfClosing: false,
  }),
  script: (props = {}, ...children) => ({
    props,
    element: 'script',
    children,
    selfClosing: false,
  }),
  section: (props = {}, ...children) => ({
    props,
    element: 'section',
    children,
    selfClosing: false,
  }),
  select: (props = {}, ...children) => ({
    props,
    element: 'select',
    children,
    selfClosing: false,
  }),
  slot: (props = {}, ...children) => ({
    props,
    element: 'slot',
    children,
    selfClosing: false,
  }),
  small: (props = {}, ...children) => ({
    props,
    element: 'small',
    children,
    selfClosing: false,
  }),
  source: (props = {}, ...children) => ({
    props,
    element: 'source',
    children,
    selfClosing: true,
  }),
  span: (props = {}, ...children) => ({
    props,
    element: 'span',
    children,
    selfClosing: false,
  }),
  strong: (props = {}, ...children) => ({
    props,
    element: 'strong',
    children,
    selfClosing: false,
  }),
  style: (props = {}, ...children) => ({
    props,
    element: 'style',
    children,
    selfClosing: false,
  }),
  sub: (props = {}, ...children) => ({
    props,
    element: 'sub',
    children,
    selfClosing: false,
  }),
  summary: (props = {}, ...children) => ({
    props,
    element: 'summary',
    children,
    selfClosing: false,
  }),
  sup: (props = {}, ...children) => ({
    props,
    element: 'sup',
    children,
    selfClosing: false,
  }),
  table: (props = {}, ...children) => ({
    props,
    element: 'table',
    children,
    selfClosing: false,
  }),
  tbody: (props = {}, ...children) => ({
    props,
    element: 'tbody',
    children,
    selfClosing: false,
  }),
  td: (props = {}, ...children) => ({
    props,
    element: 'td',
    children,
    selfClosing: false,
  }),
  template: (props = {}, ...children) => ({
    props,
    element: 'template',
    children,
    selfClosing: false,
  }),
  textarea: (props = {}, ...children) => ({
    props,
    element: 'textarea',
    children,
    selfClosing: false,
  }),
  tfoot: (props = {}, ...children) => ({
    props,
    element: 'tfoot',
    children,
    selfClosing: false,
  }),
  th: (props = {}, ...children) => ({
    props,
    element: 'th',
    children,
    selfClosing: false,
  }),
  thead: (props = {}, ...children) => ({
    props,
    element: 'thead',
    children,
    selfClosing: false,
  }),
  time: (props = {}, ...children) => ({
    props,
    element: 'time',
    children,
    selfClosing: false,
  }),
  title: (props = {}, ...children) => ({
    props,
    element: 'title',
    children,
    selfClosing: false,
  }),
  tr: (props = {}, ...children) => ({
    props,
    element: 'tr',
    children,
    selfClosing: false,
  }),
  track: (props = {}, ...children) => ({
    props,
    element: 'track',
    children,
    selfClosing: true,
  }),
  u: (props = {}, ...children) => ({
    props,
    element: 'u',
    children,
    selfClosing: false,
  }),
  ul: (props = {}, ...children) => ({
    props,
    element: 'ul',
    children,
    selfClosing: false,
  }),
  var: (props = {}, ...children) => ({
    props,
    element: 'var',
    children,
    selfClosing: false,
  }),
  video: (props = {}, ...children) => ({
    props,
    element: 'video',
    children,
    selfClosing: false,
  }),
  wbr: (props = {}, ...children) => ({
    props,
    element: 'wbr',
    children,
    selfClosing: true,
  }),
}
